"""Make filename/filepath nullable

Revision ID: 937e9f1b3ebf
Revises: 
Create Date: 2025-06-28 00:30:59.933275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '937e9f1b3ebf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_data', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_file', sa.Boolean(), nullable=True))
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('filepath',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_message', schema=None) as batch_op:
        batch_op.alter_column('filepath',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('is_file')
        batch_op.drop_column('file_data')

    # ### end Alembic commands ###
